import type { Metadata } from "next";
import { pageMetadata } from "@/lib/metadata";
import Link from "next/link";
import { LegalPage, type LegalSection } from "@/components/LegalPage";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = pageMetadata({
  title: "Privacy Policy",
  description: "How LisBran collects, uses, shares and protects personal data in line with the Kenya Data Protection Act, 2019.",
  path: "/privacy",
});

const mail = <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>;

const sections: LegalSection[] = [
  {
    id: "controller",
    title: "Who we are",
    body: (
      <p>
        {siteConfig.legalName} (&ldquo;LisBran&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) operates this marketplace from {siteConfig.address.locality},
        Kenya, and is the data controller for personal data processed through it. Contact our data protection lead at {mail} or {siteConfig.phoneDisplay}.
      </p>
    ),
  },
  {
    id: "data",
    title: "Personal data we collect",
    body: (
      <ul>
        <li><strong>Account and contact data</strong> — name, email address, phone number and password (stored hashed) when you register or contact us.</li>
        <li><strong>Vendor data</strong> — business name, category, location, portfolio images, rates, and verification details you submit when listing services.</li>
        <li><strong>Communications</strong> — messages, suggestions, survey answers and support requests you send us.</li>
        <li><strong>Preferences stored on your device</strong> — theme, chosen city and notice dismissals, kept in your browser&apos;s local storage (see our <Link href="/cookies">Cookie Policy</Link>).</li>
        <li><strong>Technical data</strong> — IP address, browser type and request logs generated by our hosting provider for security and reliability.</li>
      </ul>
    ),
  },
  {
    id: "purposes",
    title: "Why we use it and our lawful basis",
    body: (
      <ul>
        <li>To create and run your account and vendor listing — <em>performance of a contract</em>.</li>
        <li>To connect buyers with vendors and let them contact each other — <em>performance of a contract</em>.</li>
        <li>To verify vendors, prevent fraud and keep the platform secure — <em>legitimate interests</em> and <em>legal obligation</em>.</li>
        <li>To answer enquiries and provide support — <em>legitimate interests</em>.</li>
        <li>To send marketing messages — only with your <em>consent</em>, which you can withdraw at any time using the unsubscribe link or by emailing {mail}.</li>
      </ul>
    ),
  },
  {
    id: "sharing",
    title: "Who we share it with",
    body: (
      <>
        <p>We do not sell personal data. We share it only with:</p>
        <ul>
          <li><strong>Buyers and vendors</strong> — a vendor&apos;s public listing (business name, services, portfolio, contact channel) is visible to all visitors.</li>
          <li><strong>Service providers</strong> acting on our instructions: website hosting (Vercel), database and authentication (Supabase), and maps (Google Maps Platform, only when you open the map).</li>
          <li><strong>Authorities</strong> where required by Kenyan law or to protect rights and safety.</li>
        </ul>
      </>
    ),
  },
  {
    id: "transfers",
    title: "International transfers",
    body: (
      <p>
        Some of our service providers store data on servers outside Kenya. Where this happens we rely on appropriate safeguards under
        section 48 of the Data Protection Act, 2019 — such as contractual data protection commitments from the provider — and transfer only what is necessary.
      </p>
    ),
  },
  {
    id: "retention",
    title: "How long we keep it",
    body: (
      <p>
        We keep account and listing data while your account is active and for up to 24 months after closure, unless a longer period is
        required for tax, accounting or legal claims. Server logs are kept for up to 90 days. Data stored in your browser stays until you clear it.
      </p>
    ),
  },
  {
    id: "rights",
    title: "Your rights",
    body: (
      <>
        <p>Under section 26 of the Data Protection Act, 2019 you have the right to:</p>
        <ul>
          <li>be informed of how your data is used;</li>
          <li>access the personal data we hold about you;</li>
          <li>object to processing, including direct marketing;</li>
          <li>correct false or misleading data;</li>
          <li>have false, misleading or unlawfully held data deleted; and</li>
          <li>receive your data in a portable format.</li>
        </ul>
        <p>
          Email {mail} to exercise any of these. We will respond within the timelines set by the Data Protection (General) Regulations, 2021.
          If you are unhappy with our response you may complain to the Office of the Data Protection Commissioner at{" "}
          <a href="https://www.odpc.go.ke" target="_blank" rel="noopener noreferrer">www.odpc.go.ke</a>.
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "Security",
    body: (
      <p>
        We use encryption in transit (HTTPS), access controls, and reputable infrastructure providers to protect personal data. No system is
        perfectly secure; if we become aware of a breach affecting you we will notify you and the Data Commissioner as required by law.
      </p>
    ),
  },
  {
    id: "children",
    title: "Children",
    body: <p>LisBran is intended for users aged 18 and over. We do not knowingly collect data from children.</p>,
  },
  {
    id: "changes",
    title: "Changes to this policy",
    body: <p>We may update this policy from time to time. The &ldquo;last updated&rdquo; date above shows when it last changed; material changes will be highlighted on the site.</p>,
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      intro={<p>This policy explains how LisBran handles your personal data when you use our website and marketplace, in line with the Kenya Data Protection Act, 2019.</p>}
      sections={sections}
    />
  );
}
